name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.16.1
        
    - name: Checkout the repository
      uses: actions/checkout@master
      
    - name: Install Dependencies
      run: npm install
    
    - name: Build for production
      run: npm run build
      
    - name: Deploy script to gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: 26433a26b29cef790d2302703bab980d
        gist_file_name: avotalif.user.js
        file_path: ./dist/avotalif.user.js
        
    - name: Deploy meta to gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: 26433a26b29cef790d2302703bab980d
        gist_file_name: avotalif.meta.js
        file_path: ./dist/avotalif.meta.js 
